-- 132_ifrs16_backend_hardening_and_crud.sql
-- Hardens IFRS 16 backend behavior for exempt leases, CRUD corrections, and measurement snapshots.

BEGIN;

-- Exempt leases only need an expense account and cash/bank account. On-balance-sheet
-- leases are still validated at the application layer to require full IFRS 16 mappings.
ALTER TABLE leases
  ALTER COLUMN rou_asset_account_id DROP NOT NULL,
  ALTER COLUMN lease_liability_account_id DROP NOT NULL,
  ALTER COLUMN interest_expense_account_id DROP NOT NULL,
  ALTER COLUMN depreciation_expense_account_id DROP NOT NULL,
  ALTER COLUMN accumulated_depreciation_account_id DROP NOT NULL,
  ALTER COLUMN cash_account_id DROP NOT NULL;

-- Preserve the existing column for compatibility but document its intended meaning.
COMMENT ON COLUMN leases.monthly_depreciation_amount IS
  'Compatibility field: stores the periodic depreciation amount generated by the current IFRS 16 schedule, not necessarily a calendar-month amount.';

ALTER TABLE lease_measurement_snapshots
  ADD COLUMN IF NOT EXISTS purchase_option_amount numeric(18,6);

CREATE INDEX IF NOT EXISTS idx_leases_org_status_recognition
  ON leases(organization_id, status, recognition_model);

CREATE INDEX IF NOT EXISTS idx_lease_contracts_currency
  ON lease_contracts(organization_id, currency_code);

COMMIT;
