const {AppError}=require('../../../shared/errors/AppError');
const {pool}=require('../../../db/pool');
const {moneyUnits,moneyStringFromUnits}=require('../../../shared/utils/financialMath');
function integer(value,fallback,max){const n=Number.parseInt(value??fallback,10);return Number.isFinite(n)?Math.min(Math.max(n,0),max):fallback;}
async function listCashbook(orgId,query={}){
 const limit=Math.max(1,integer(query.limit,200,500)),offset=integer(query.offset,0,1000000000);const bankAccountId=query.bankAccountId||query.bank_account_id||null,glAccountId=query.glAccountId||query.gl_account_id||null,dateFrom=query.dateFrom||query.date_from||null,dateTo=query.dateTo||query.date_to||null,includeRunning=String(query.includeRunningBalance||query.include_running_balance||'false').toLowerCase()==='true',sort=String(query.sort||'desc').toLowerCase()==='asc'?'asc':'desc';
 let resolvedBankAccountId=bankAccountId;if(!resolvedBankAccountId&&glAccountId){const{rows}=await pool.query(`SELECT id FROM bank_accounts WHERE organization_id=$1 AND gl_account_id=$2 LIMIT 1`,[orgId,glAccountId]);if(rows.length)resolvedBankAccountId=rows[0].id;}
 if(resolvedBankAccountId){const{rows}=await pool.query(`SELECT id,currency_code FROM bank_accounts WHERE organization_id=$1 AND id=$2`,[orgId,resolvedBankAccountId]);if(!rows.length)throw new AppError(404,'Bank account not found');}
 if(!resolvedBankAccountId&&!glAccountId)throw new AppError(400,'bankAccountId or glAccountId is required for cashbook view');const effectiveSort=includeRunning&&sort==='desc'&&String(query.runningPrefersAsc||'true').toLowerCase()==='true'?'asc':sort;
 if(resolvedBankAccountId){const params=[orgId,resolvedBankAccountId];let where='WHERE bt.organization_id=$1 AND bt.bank_account_id=$2';if(dateFrom){params.push(dateFrom);where+=` AND bt.txn_date >= $${params.length}`;}if(dateTo){params.push(dateTo);where+=` AND bt.txn_date <= $${params.length}`;}
  const{rows:sum}=await pool.query(`SELECT
   COALESCE((SELECT SUM(x.amount) FROM bank_transactions x WHERE x.organization_id=$1 AND x.bank_account_id=$2 ${dateFrom?'AND x.txn_date < $3':''}),0)::numeric AS opening_balance,
   COALESCE(SUM(CASE WHEN bt.amount>0 THEN bt.amount ELSE 0 END),0)::numeric AS total_in,
   COALESCE(SUM(CASE WHEN bt.amount<0 THEN -bt.amount ELSE 0 END),0)::numeric AS total_out,
   COALESCE(SUM(bt.amount),0)::numeric AS net FROM bank_transactions bt ${where}`,params);
  const summary=sum[0]||{};const opening=String(summary.opening_balance||'0');params.push(limit,offset);const running=includeRunning?`, ($${params.length+1}::numeric + SUM(bt.amount) OVER (PARTITION BY bt.bank_account_id ORDER BY bt.txn_date ${effectiveSort.toUpperCase()},bt.created_at ${effectiveSort.toUpperCase()},bt.id ${effectiveSort.toUpperCase()} ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW)) AS running_balance`:'';if(includeRunning)params.push(opening);
  const{rows}=await pool.query(`SELECT bt.id,bt.bank_account_id,ba.code AS bank_account_code,ba.name AS bank_account_name,ba.currency_code,bt.txn_date,bt.amount,bt.description,bt.reference,bt.source_type,bt.source_id,bt.statement_line_id,bt.journal_entry_id,je.entry_no AS journal_entry_no,bt.external_id,bt.created_at,m.journal_entry_id AS matched_journal_entry_id,m.matched_at,m.matched_by${running}
   FROM bank_transactions bt JOIN bank_accounts ba ON ba.id=bt.bank_account_id AND ba.organization_id=bt.organization_id LEFT JOIN bank_matches m ON m.bank_statement_line_id=bt.statement_line_id LEFT JOIN journal_entries je ON je.id=bt.journal_entry_id AND je.organization_id=bt.organization_id ${where}
   ORDER BY bt.txn_date ${effectiveSort.toUpperCase()},bt.created_at ${effectiveSort.toUpperCase()} LIMIT $${params.length-(includeRunning?2:1)} OFFSET $${params.length-(includeRunning?1:0)}`,params);
  const net=String(summary.net||'0');const closing=moneyStringFromUnits(moneyUnits(opening)+moneyUnits(net));return{mode:'bank',data:rows,summary:{openingBalance:opening,closingBalance:closing,totalIn:String(summary.total_in||'0'),totalOut:String(summary.total_out||'0'),net},paging:{limit,offset,sort:effectiveSort}};
 }
 const params=[orgId,glAccountId];let where=`WHERE je.organization_id=$1 AND je.status='posted' AND jel.account_id=$2`;if(dateFrom){params.push(dateFrom);where+=` AND je.entry_date >= $${params.length}`;}if(dateTo){params.push(dateTo);where+=` AND je.entry_date <= $${params.length}`;}
 const openingParams=[orgId,glAccountId];let openingWhere=`WHERE je.organization_id=$1 AND je.status='posted' AND jel.account_id=$2`;if(dateFrom){openingParams.push(dateFrom);openingWhere+=` AND je.entry_date < $3`;}else openingWhere+=' AND FALSE';const{rows:ob}=await pool.query(`SELECT COALESCE(SUM(COALESCE(jel.amount_base,COALESCE(jel.debit,0)-COALESCE(jel.credit,0))),0)::numeric AS opening FROM journal_entries je JOIN journal_entry_lines jel ON jel.journal_entry_id=je.id ${openingWhere}`,openingParams);const opening=String(ob[0]?.opening||'0');
 const{rows:tt}=await pool.query(`SELECT COALESCE(SUM(CASE WHEN COALESCE(jel.amount_base,COALESCE(jel.debit,0)-COALESCE(jel.credit,0))>0 THEN COALESCE(jel.amount_base,COALESCE(jel.debit,0)-COALESCE(jel.credit,0)) ELSE 0 END),0)::numeric AS total_in,COALESCE(SUM(CASE WHEN COALESCE(jel.amount_base,COALESCE(jel.debit,0)-COALESCE(jel.credit,0))<0 THEN -COALESCE(jel.amount_base,COALESCE(jel.debit,0)-COALESCE(jel.credit,0)) ELSE 0 END),0)::numeric AS total_out,COALESCE(SUM(COALESCE(jel.amount_base,COALESCE(jel.debit,0)-COALESCE(jel.credit,0))),0)::numeric AS net FROM journal_entries je JOIN journal_entry_lines jel ON jel.journal_entry_id=je.id ${where}`,params);const sum=tt[0]||{};const net=String(sum.net||'0');const closing=moneyStringFromUnits(moneyUnits(opening)+moneyUnits(net));params.push(limit,offset);const running=includeRunning?`, ($${params.length+1}::numeric + SUM(COALESCE(jel.amount_base,COALESCE(jel.debit,0)-COALESCE(jel.credit,0))) OVER (ORDER BY je.entry_date ${effectiveSort.toUpperCase()},je.created_at ${effectiveSort.toUpperCase()},je.id ${effectiveSort.toUpperCase()} ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW)) AS running_balance`:'';if(includeRunning)params.push(opening);const{rows}=await pool.query(`SELECT je.id AS journal_entry_id,je.entry_date AS txn_date,COALESCE(jel.amount_base,COALESCE(jel.debit,0)-COALESCE(jel.credit,0)) AS amount,COALESCE(jel.description,je.memo) AS description,je.id::text AS reference,'journal' AS source_type,je.id AS source_id,je.created_at${running} FROM journal_entries je JOIN journal_entry_lines jel ON jel.journal_entry_id=je.id ${where} ORDER BY je.entry_date ${effectiveSort.toUpperCase()},je.created_at ${effectiveSort.toUpperCase()} LIMIT $${params.length-(includeRunning?2:1)} OFFSET $${params.length-(includeRunning?1:0)}`,params);return{mode:'gl',glAccountId,data:rows,summary:{openingBalance:opening,closingBalance:closing,totalIn:String(sum.total_in||'0'),totalOut:String(sum.total_out||'0'),net},paging:{limit,offset,sort:effectiveSort}};
}
module.exports={listCashbook};
